### ISSUE TITLE
[BE] 로깅 파이프라인을 위한 Kafka 종속성 추가 및 설정 클래스 생성한다.

### ISSUE THREAD

**Issue by Bangseungjae** [sss-develops/query-server#8]
## 📌 상세 내용
- Kafka Dependency 추가
- Kafka 설정 클래스 생성

## 🌠  구현내용 
- [x] build.gradle에 dependency추가
- [x] 카프카 설정 클래스 생성

**Comment by JWJung-01** [comment]
승재님~ 제목 양식 맞춰주셔요 🫣

**Comment by Bangseungjae** [comment]
넵
